apiVersion: v1
kind: Service
metadata:
  name: {{ include "neurosynth.fullname" . }}-api
spec:
  selector: {app: neurosynth-api}
  ports:
  - port: {{ .Values.api.servicePort }}
    targetPort: {{ .Values.api.containerPort }}
