apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "neurosynth.fullname" . }}-ingress
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className }}
    alb.ingress.kubernetes.io/scheme: {{ .Values.ingress.scheme | default "internal" }}
    {{- if .Values.ingress.wafAclArn }}
    alb.ingress.kubernetes.io/wafv2-acl-arn: {{ .Values.ingress.wafAclArn | quote }}
    {{- end }}
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "neurosynth.fullname" . }}-api
            port:
              number: {{ .Values.api.servicePort }}
