apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "neurosynth.fullname" . }}-sa
  {{- if .Values.serviceAccount.irsaRoleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.irsaRoleArn | quote }}
  {{- end }}
