# AI Assistance: Developed with assistance from Claude (Anthropic) — claude.ai
"""v3 Clinical Report Generator — live Claude LLM SOAP narrative (Gap 4).

Extends :class:`ClinicalReportGeneratorV2`. When an Anthropic API key is configured
the SOAP narrative is generated by Claude and every risk percentage it states is
verified against the inference payload (hallucination guard). When no key is set, or
the API call / verification fails, it transparently falls back to the deterministic
Jinja2 template path from v2 — so the endpoint always returns a usable report.

The report dict gains a ``generated_by`` field:
  - ``"claude:<model>"`` when the LLM path succeeded
  - ``"jinja2-template"`` otherwise
"""
from __future__ import annotations

import logging
import os
import re
from datetime import datetime, timezone
from typing import Any

from backend.report_generator_v2 import ClinicalReportGeneratorV2

logger = logging.getLogger(__name__)

SOAP_SYSTEM_PROMPT = """You are a board-certified neurologist writing a clinical \
risk-assessment note for a colleague. You are given the structured output of an AI \
neurological risk model. Write a SOAP note from it.

Hard rules:
1. Output ONLY valid JSON with exactly these keys: "subjective", "objective", \
"assessment", "plan". Each value is a single prose string.
2. Never state a fact, measurement, or percentage that is not present in the provided \
data. Do NOT invent population statistics or comparison figures.
3. The ONLY percentage you may write is the model's risk probability, stated once in \
the Assessment. Do not write any other percentage anywhere.
4. Use hedged clinical language: "findings are consistent with", "suggestive of", \
"warrants further evaluation". Never assert a diagnosis with certainty.
5. In the Assessment, name the suspected condition with its ICD-10 code in parentheses.
6. Keep the Assessment to at most 3 sentences. The Plan must include at least one \
follow-up recommendation with an explicit timeframe.
7. Do not use the word "likely" unless immediately followed by the risk percentage."""


class HallucinationError(ValueError):
    """Raised when the LLM report states a risk figure not supported by the payload."""


class ClinicalReportGeneratorV3(ClinicalReportGeneratorV2):
    """Claude-backed clinical report generator with deterministic fallback."""

    def __init__(
        self,
        hf_token: str | None = None,
        api_key: str | None = None,
        model: str | None = None,
    ) -> None:
        super().__init__(hf_token=hf_token)

        resolved_key = api_key
        resolved_model = model
        if resolved_key is None or resolved_model is None:
            try:
                from backend.core.config import get_settings

                settings = get_settings()
                resolved_key = resolved_key if resolved_key is not None else settings.anthropic_api_key
                resolved_model = resolved_model if resolved_model is not None else settings.anthropic_model
            except Exception:  # pragma: no cover - config optional at import time
                resolved_key = resolved_key or os.getenv("ANTHROPIC_API_KEY", "")
                resolved_model = resolved_model or "claude-sonnet-4-6"

        self.api_key = resolved_key or os.getenv("ANTHROPIC_API_KEY", "")
        self.model = resolved_model or "claude-sonnet-4-6"
        self._client = self._init_client()

    def _init_client(self) -> Any | None:
        if not self.api_key:
            return None
        try:
            import anthropic

            return anthropic.Anthropic(api_key=self.api_key)
        except Exception as exc:  # pragma: no cover - import/runtime guard
            logger.warning("anthropic_client_init_failed error=%s", exc)
            return None

    @property
    def llm_enabled(self) -> bool:
        return self._client is not None

    # ------------------------------------------------------------------
    # Core generate (override) — build v2 report, then enrich with LLM
    # ------------------------------------------------------------------

    def generate_report(
        self,
        patient_data: dict[str, Any],
        prediction: dict[str, Any],
        trajectory: list[float],
        causal_graph: dict[str, Any],
        shap_values: list[dict[str, Any]],
        patient_id: str = "P-000",
        disease: str | None = None,
    ) -> dict[str, Any]:
        report = super().generate_report(
            patient_data, prediction, trajectory, causal_graph,
            shap_values, patient_id, disease,
        )
        report["generated_by"] = "jinja2-template"

        if not self.llm_enabled:
            return report

        try:
            soap = self._generate_soap_llm(
                patient_data, prediction, trajectory, causal_graph, shap_values, disease,
            )
            self._verify_report_facts(soap, prediction)
        except HallucinationError as exc:
            logger.warning("llm_report_hallucination_guard_tripped error=%s", exc)
            return report
        except Exception as exc:
            logger.warning("llm_report_generation_failed error=%s", exc)
            return report

        report.update(
            self._merge_llm_soap(report, soap, prediction, trajectory, shap_values)
        )
        report["generated_by"] = f"claude:{self.model}"
        return report

    def _merge_llm_soap(
        self,
        report: dict[str, Any],
        soap: dict[str, str],
        prediction: dict[str, Any],
        trajectory: list[float],
        shap_values: list[dict[str, Any]],
    ) -> dict[str, Any]:
        sections = {
            "1. SUBJECTIVE": soap["subjective"],
            "2. OBJECTIVE": soap["objective"],
            "3. ASSESSMENT": soap["assessment"],
            "4. PLAN": soap["plan"],
        }
        raw_text = "\n\n".join(f"{k}\n{v}" for k, v in sections.items())

        traj_text = ""
        if trajectory:
            months = [6, 12, 18, 24, 30, 36, 42, 48][: len(trajectory)]
            traj_text = " → ".join(f"Mo {m}: {v:.1%}" for m, v in zip(months, trajectory))

        html = self._template.render(
            patient_id=report.get("patient_id", "P-000"),
            generated_at=report.get("generated_at", datetime.now(timezone.utc).isoformat()),
            report_id=report.get("report_id", ""),
            probability=prediction.get("probability", 0.5),
            risk_level=prediction.get("risk_level", "Unknown"),
            confidence=prediction.get("confidence", "Medium"),
            subjective=soap["subjective"],
            objective=soap["objective"],
            assessment=soap["assessment"],
            plan=soap["plan"],
            icd_codes=report.get("icd10_codes", []),
            trajectory=trajectory,
            trajectory_text=traj_text,
            top_risk_factors=shap_values[:5],
        )
        return {
            "soap": soap,
            "sections": sections,
            "raw_text": raw_text,
            "html": html,
            "word_count": len(raw_text.split()),
        }

    # ------------------------------------------------------------------
    # LLM call
    # ------------------------------------------------------------------

    def _generate_soap_llm(
        self,
        patient_data: dict[str, Any],
        prediction: dict[str, Any],
        trajectory: list[float],
        causal_graph: dict[str, Any],
        shap_values: list[dict[str, Any]],
        disease: str | None,
    ) -> dict[str, str]:
        prob = float(prediction.get("probability", 0.5))
        risk = prediction.get("risk_level", "Unknown")
        cond = disease or prediction.get("disease", "Alzheimer's Disease")
        top_shap = [
            f"{r.get('feature')} ({float(r.get('value', 0.0)):+.4f})" for r in shap_values[:5]
        ] or ["none available"]
        top_causes = [
            c.get("variable") for c in causal_graph.get("top_causes_of_Diagnosis", [])
        ][:3] or ["none available"]
        traj_summary = ""
        if trajectory:
            months = [6, 12, 18, 24, 30, 36, 42, 48][: len(trajectory)]
            traj_summary = ", ".join(f"month {m}: {v:.1%}" for m, v in zip(months, trajectory))

        user_content = (
            "Generate a clinical SOAP note from this neurological risk analysis.\n\n"
            f"Suspected condition: {cond}\n"
            f"Model risk probability: {prob:.1%} ({risk} risk) — this is the ONLY "
            "percentage you may cite.\n"
            f"Top risk factors (SHAP): {', '.join(top_shap)}\n"
            f"Causal drivers: {', '.join(str(c) for c in top_causes)}\n"
            f"48-month trajectory: {traj_summary or 'not available'}\n"
            f"Patient: Age {patient_data.get('Age', 'N/A')}, "
            f"MMSE {patient_data.get('MMSE', 'N/A')}/30, "
            f"Functional assessment {patient_data.get('FunctionalAssessment', 'N/A')}/10, "
            f"ADL {patient_data.get('ADL', 'N/A')}/10."
        )

        message = self._client.messages.create(
            model=self.model,
            max_tokens=1500,
            system=SOAP_SYSTEM_PROMPT,
            messages=[{"role": "user", "content": user_content}],
        )
        text = "".join(
            getattr(block, "text", "") for block in message.content
            if getattr(block, "type", "") == "text"
        )
        return self._parse_soap_json(text)

    @staticmethod
    def _parse_soap_json(text: str) -> dict[str, str]:
        import json

        match = re.search(r"\{.*\}", text, re.DOTALL)
        if not match:
            raise ValueError("LLM response contained no JSON object")
        data = json.loads(match.group(0))
        required = ("subjective", "objective", "assessment", "plan")
        if not all(k in data and str(data[k]).strip() for k in required):
            raise ValueError("LLM JSON missing required SOAP keys")
        return {k: str(data[k]).strip() for k in required}

    # ------------------------------------------------------------------
    # Hallucination guard
    # ------------------------------------------------------------------

    @staticmethod
    def _verify_report_facts(soap: dict[str, str], prediction: dict[str, Any], tol: float = 0.12) -> None:
        """Ensure every percentage stated in the report is supported by the payload."""
        known: list[float] = []
        prob = prediction.get("probability")
        if isinstance(prob, (int, float)):
            known.append(float(prob))
        for value in (prediction.get("disease_probabilities") or {}).values():
            if isinstance(value, (int, float)):
                known.append(float(value))
        if not known:
            return

        text = " ".join(soap.values())
        for raw in re.findall(r"(\d+(?:\.\d+)?)\s*%", text):
            pct = float(raw) / 100.0
            if min(abs(pct - k) for k in known) > tol:
                raise HallucinationError(
                    f"report cites {raw}% but no model probability is within {tol:.0%} "
                    f"(known: {[round(k, 3) for k in known]})"
                )
